name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    environment:
      name: Staging

    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v1

    # Install package
    - name: Install package
      run: composer install

    # Run test PSR-12 convention
    - name: Run process linter
      run: composer lint

    # Run decrypt secret passphrase to create laravel-config-firebase.json file
    - name: Decrypt secret passphrase
      run: ./.github/scripts/decrypt_secret.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

    # Run test for package
    - name: Run phpunit
      run: vendor/bin/phpunit --coverage-clover coverage.xml

    # Run performance test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          file: ./coverage.xml
