name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    environment:
      name: Staging

    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - name: Checkout code
      uses: actions/checkout@v1

    # Install package
    - name: Install package
      run: composer install
      env:
          FIREBASE_CREDENTIALS: ./laravel-config-firebase.json

    # Run test PSR-12 convention
    - name: Run process linter
      run: composer lint

    # Run test
    # - name: Run create firebase credential file
    #  run: echo -n -e "${{ secrets.FIREBASE_CREDENTIALS }}" > ./laravel-config-firebase.json

    # Run test
    # - name: Run gpg
    #  run: gpg --symmetric --cipher-algo AES256 ./laravel-config-firebase.json

    - name: Decrypt large secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/secrets/laravel-config-firebase.json

    # Run test for package
    - name: Run phpunit
      run: vendor/bin/phpunit --coverage-clover coverage.xml

    # Run performance test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          file: ./coverage.xml
